// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKvr5gFK2bo-Xge4_PNkdefMtIxLkm9U',
    appId: '1:199702173841:web:ef0285d59922aa2c4e4730',
    messagingSenderId: '199702173841',
    projectId: 'productive-u-56b60',
    authDomain: 'productive-u-56b60.firebaseapp.com',
    storageBucket: 'productive-u-56b60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgzqdWGBeUKmJo43x8xYI9HfMPfqY4dk',
    appId: '1:199702173841:android:1e74093b786f54414e4730',
    messagingSenderId: '199702173841',
    projectId: 'productive-u-56b60',
    storageBucket: 'productive-u-56b60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ6Hg8hsIY8ZpZOpGXrV6uFehC6xQ9W9w',
    appId: '1:199702173841:ios:4bc5cf8fa4a733204e4730',
    messagingSenderId: '199702173841',
    projectId: 'productive-u-56b60',
    storageBucket: 'productive-u-56b60.firebasestorage.app',
    iosBundleId: 'com.example.productiveu',
  );

}